# Generated by Django 4.0.6 on 2022-08-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_skill_created_alter_skill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='decription',
            new_name='description',
        ),
    ]
